### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by thoms3n** [Spanni26/pyHPSU#27]
Have the following Error:
(paho-mqtt in /usr/local/lib/python3.5/dist-packages (1.5.0))

```
python3 /usr/bin/pyHPSU.py -c t_hs -o mqtt
Traceback (most recent call last):
  File "/usr/bin/pyHPSU.py", line 335, in <module>
    main(sys.argv[1:])
  File "/usr/bin/pyHPSU.py", line 275, in main
    read_can(driver, logger, port, cmd, lg_code,verbose,output_type)
  File "/usr/bin/pyHPSU.py", line 332, in read_can
    hpsu_plugin.pushValues(vars=arrResponse)
  File "/usr/lib/python3/dist-packages/HPSU/plugins/mqtt.py", line 94, in pushValues
    ret=self.client.publish(self.prefix + "/" + r['name'],payload=r['resp'], qos=self.qos)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1247, in publish
    if qos < 0 or qos > 2:
TypeError: unorderable types: str() < int()

```
Is this a known issue?

**Comment by Spanni26** [comment]
Should be fixed.
